---

- name: Install Craft CMS database and initial project
  become_user: "{{ craft_user }}"
  shell: >
    php craft install/craft
    --interactive 0
    --username '{{ craft_app_user }}'
    --password '{{ craft_app_pass }}'
    --email '{{ craft_app_email }}'
    --site-name '{{ craft_app_sitename }}'
    --site-url '{{ craft_app_siteurl }}'
    --language 'en-US'
  args:
    chdir: "{{ craft_install_path }}"
    creates: "{{ craft_install_path }}/config/project"
