---

- name: Create HTTP log directory
  file:
    path: "/var/log/httpd/{{ craft_project_name }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: Put in place HTTPD virtual host configuration
  template:
    src: "craft_vhost.j2"
    dest: "/etc/httpd/vhosts.d/{{ craft_project_name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Adjust Apache config to run as craft user 
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^User"
      line: "User {{ craft_user }}"
    - regexp: "^Group"
      line: "Group {{ craft_user }}"

- name: Adjust PHP-FPM config to run as craft user 
  lineinfile: 
    path: "{{ craft_php_fpm_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^user"
      line: "user = {{ craft_user }}"
    - regexp: "^group"
      line: "group = {{ craft_user }}"