---

- name: Get path to PHP executable
  become_user: "{{ craft_user }}"
  shell: >
    which php
  register: php_exec

- name: Install Craft CMS database and initial project
  become_user: "{{ craft_user }}"
  command: >
    {{ php_exec.stdout }} craft install/craft
    --interactive 0
    --username '{{ craft_app_user }}'
    --password '{{ craft_app_pass }}'
    --email '{{ craft_app_email }}'
    --site-name '{{ craft_app_sitename }}'
    --site-url '{{ craft_app_siteurl }}'
    --language 'en-US'
  args:
    chdir: "{{ craft_install_path }}"
    creates: "{{ craft_install_path }}/config/project/project.yml"
