---

- name: Create Craft CMS group
  group:
    name: "{{ craft_user }}"
    state: "present"

- name: Create Craft CMS user
  user:
    name: "{{ craft_user }}"
    group: "{{ craft_user }}"
    shell: "/bin/bash"
    home: "/home/{{ craft_user }}"
    comment: "Craft CMS User Account"
    state: "present"

- name: Create Craft CMS web directory
  file:
    path: "{{  craft_install_path  }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    mode: "0755"
    state: "directory"

- name: Download and Unarchive Craft CMS files
  unarchive:
    remote_src: "yes"
    src: "{{ craft_download_url }}"
    dest: "{{ craft_install_path }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    creates: "{{ craft_install_path }}/config"

- name: Set ownership of Craft CMS files
  file:
    path: "{{  craft_install_path  }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    state: "directory"
    recurse: "yes"

- name: Create subdirectories within the storage directory
  file:
    path: "{{  craft_install_path  }}/storage/{{ item }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    state: "directory"
    mode: "0775"
  loop:
    - "runtime"
    - "logs"

- name: Adjust permissions of certain files to allow writing by PHP and Craft
  file:
    path: "{{  craft_install_path  }}/{{ item }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    mode: "0660"
  loop:
    - "composer.json"
    - "composer.lock"

- name: Adjust permissions of certain directories to allow writing by PHP and Craft
  command: >
    find {{ craft_install_path }}/{{ item }} -type d -exec chmod 0775 {} \;
  loop:
    - "config"
    - "storage"
    - "vendor"
    - "web/cpresources"

- name: Adjust Apache config to run as craft user 
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^User"
      line: "User {{ craft_user }}"
    - regexp: "^Group"
      line: "Group {{ craft_user }}"

- name: Adjust PHP-FPM config to run as craft user 
  lineinfile: 
    path: "/etc/opt/rh/rh-php73/php-fpm.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^user"
      line: "user = {{ craft_user }}"
    - regexp: "^group"
      line: "group = {{ craft_user }}"

- name: Create craft assets directory mount point 
  file: 
    path: "{{ craft_assets_dir }}"
    owner: "{{ craft_user }}"
    group: "{{ craft_user }}"
    mode: "0755"
    state: "directory"

- block:
  - name: Create fstab entry for craft assets volume and mount it
    mount:
      path: "{{ craft_assets_dir }}"
      src: "{{ craft_assets_volume_path }}"
      fstype: "{{ craft_assets_volume_fstype }}"
      opts: "{{ craft_assets_volume_opts }}"
      state: "mounted"

  - name: Ensure correct ownership of craft assets dir once mounted 
    file: 
      path: "{{ craft_assets_dir }}"
      owner: "{{ craft_user }}"
      group: "{{ craft_user }}"
      state: "directory"
      recurse: "yes"
  when: craft_assets_external_mount == "yes"